# Generated by GitHub Copilot on 2025-12-23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyticsdata",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="analyticsdata",
            name="free_spaces",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analyticsdata",
            name="occupied_spaces",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analyticsdata",
            name="source",
            field=models.CharField(default="unknown", max_length=20),
        ),
        migrations.AddField(
            model_name="analyticsdata",
            name="total_spaces",
            field=models.IntegerField(default=0),
        ),
    ]
